### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by pinage404** [lapp0/nix-gui#4]
Hi

I just tried to run it, but it didn't work

```
nixFlakes run github:lapp0/nix-gui
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
Traceback (most recent call last):
  File "/nix/store/q3yrkldj3jh44z1n4w6i8pa50jcs0sii-python3.8-nix-gui-0.1.0/bin/.nix-gui-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/q3yrkldj3jh44z1n4w6i8pa50jcs0sii-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/gui.py", line 66, in main
    statemodel = state_model.StateModel()
  File "/nix/store/q3yrkldj3jh44z1n4w6i8pa50jcs0sii-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/state_model.py", line 14, in __init__
    for opt in api.get_options_dict().keys()
  File "/nix/store/q3yrkldj3jh44z1n4w6i8pa50jcs0sii-python3.8-nix-gui-0.1.0/lib/python3.8/site-packages/nixui/api.py", line 13, in get_options_dict
    res = json.load(open('./release_out/share/doc/nixos/options.json'))
FileNotFoundError: [Errno 2] No such file or directory: './release_out/share/doc/nixos/options.json'
```

What should I do to be able to run it ?

**Comment by lapp0** [comment]
This is bad documentation on my part. You need to run `nixui/load.sh` to load the options. Leaving this open as a documentation issue.

**Comment by shimunn** [comment]
That script doesn't seem to be checked into this repo

**Comment by lapp0** [comment]
@shimunn thanks for testing out the program. https://github.com/lapp0/nix-gui/pull/7 removes the need for `load.sh`. Now the application runs the appropriate command and caches the result to `~/.config/nixgui`

`CONFIGURATION_PATH=/etc/nixos/configuration.nix nix run github:lapp0/nix-gui= worked for me in master in a clean directory`
